### ISSUE TITLE
Getting issue "Unable to cast object of type "UassetAPI...." when attempting to modify soft package references.

### ISSUE THREAD

**Issue by haayfe** [atenfyr/UAssetGUI#95]
Game: Sea of Thieves
UE4 Version: 4.10.4
Attempting to modify: Wieldable blueprint for weapon

Error message: Unhandled exception has occurred in your application. If you click Continue, the application will ignore this emor and attempt to continue. If you click Quit, the application will close immediately. Unable to cast object of type 'UAssetAPl .UnrealTypes.FString' to type 'System.String•.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'UAssetAPI.UnrealTypes.FString' to type 'System.String'.
   at UAssetGUI.TableHandler.Save(Boolean forceNewLoad)
   at UAssetGUI.Form1.dataGridEditCell(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnCellValueChanged(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.SetValue(Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridView.PushFormattedValue(DataGridViewCell& dataGridViewCurrentCell, Object formattedValue, Exception& exception)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context, Boolean forCurrentCellChange, Boolean forCurrentRowChange)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

If anyone can help me that'd be much appreciated!

Note: I have to use version 1.0.08 because I am unable to load up the uasset in 1.0.1.

**Comment by atenfyr** [comment]
Can you provide a copy of an asset you are having this problem with?

**Comment by haayfe** [comment]
I've attached the asset to this comment though the same error seems to affect any uasset I attempt to edit

[bp_wpn_blunderbuss_kra_01_a_wieldable.zip](https://github.com/user-attachments/files/16522016/bp_wpn_blunderbuss_kra_01_a_wieldable.zip)
